#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: v1
kind: ConfigMap
data:
  RUNTIME_ENV: #@ data.values.env
metadata:
  name: spring-petclinic-cm
  labels: 
     obj_label:  "cm"
