#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: v1
data:
  RUNTIME_ENV: dev
kind: ConfigMap
metadata:
  labels:
    app: spring-petclinic-dev
  name: runtime-env-cm
  namespace: #@ data.values.namespace