#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if/end data.values.create_ingress:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels: 
    obj_label: ingress
spec:
  rules:
  - http:
      paths:
      - path:  #@ "/"  + data.values.env
        backend:
          serviceName: spring-petclinic-svc
          servicePort: 8080
