#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ prefix = data.values.prefix or ""

#@ if/end data.values.create_ingress:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: #@ prefix + str("ingress")
  labels: 
    deployment_label: #@ prefix + str("ingress")
spec:
  rules:
  - http:
      paths:
      - path:  #@ str("/")  + data.values.env
        backend:
          serviceName: spring-petclinic-svc
          servicePort: 8080
