#@data/values
---
env: dev
optionalPrefix: dev-
namespace: dev-spring-petclinic
app_name: spring-petclinic-app
svc_external_ip: false
create_ingress: true
image: docker.io/andriykalashnykov/spring-petclinic:1.1